# Generated by Django 5.1.3 on 2024-11-25 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('description', models.TextField(blank=True)),
                ('hit_dice', models.IntegerField(choices=[(4, 'D4'), (6, 'D6'), (8, 'D8'), (10, 'D10'), (12, 'D12'), (20, 'D20')], default=None, null=True)),
                ('num_dice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('modifier', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ammunition', models.BooleanField(default=False)),
                ('finesse', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('light', models.BooleanField(default=False)),
                ('loading', models.BooleanField(default=False)),
                ('range', models.BooleanField(default=False)),
                ('reach', models.BooleanField(default=False)),
                ('shield', models.BooleanField(default=False)),
                ('special', models.BooleanField(default=False)),
                ('thrown', models.BooleanField(default=False)),
                ('two_handed', models.BooleanField(default=False)),
                ('versatile', models.BooleanField(default=False)),
                ('min_range', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('max_range', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
