# Generated by Django 5.1.3 on 2024-11-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayablecharacter',
            name='l_hand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_playable_l_hand', to='action.weapon'),
        ),
        migrations.AddField(
            model_name='nonplayablecharacter',
            name='r_hand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_playable_r_hand', to='action.weapon'),
        ),
        migrations.AddField(
            model_name='playablecharacter',
            name='l_hand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playable_l_hand', to='action.weapon'),
        ),
        migrations.AddField(
            model_name='playablecharacter',
            name='r_hand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playable_r_hand', to='action.weapon'),
        ),
    ]
