# Generated by Django 5.0.4 on 2024-06-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('name_background', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('name_feature', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('description_feature', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name_language', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_proficiency', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description_proficiency', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_bond', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
                ('background_bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background', verbose_name='Trasfondo')),
            ],
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_flaw', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
                ('background_flaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background', verbose_name='Trasfondo')),
            ],
        ),
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ideal', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
                ('background_ideal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background', verbose_name='Trasfondo')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_personality', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
                ('background_personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background', verbose_name='Trasfondo')),
            ],
        ),
        migrations.AddField(
            model_name='background',
            name='proficiencies_background',
            field=models.ManyToManyField(to='traits.proficiency', verbose_name='Competencias'),
        ),
    ]
