# Generated by Django 5.0.4 on 2024-07-02 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('language_choices', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('max_tool_proficiencies_choices', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('skills', models.ManyToManyField(max_length=2, to='rules.skill')),
                ('tool_proficiencies_choices', models.ManyToManyField(to='actions.tool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hit_dice', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(4)])),
                ('st_str', models.BooleanField(default=False)),
                ('st_dex', models.BooleanField(default=False)),
                ('st_con', models.BooleanField(default=False)),
                ('st_int', models.BooleanField(default=False)),
                ('st_wis', models.BooleanField(default=False)),
                ('st_cha', models.BooleanField(default=False)),
                ('can_spellcasting', models.BooleanField(default=False)),
                ('max_tool_proficiencies_choices', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('max_skill_choices', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('armor_proficiencies', models.ManyToManyField(to='actions.armor')),
                ('skill_choices', models.ManyToManyField(to='rules.skill')),
                ('tool_proficiencies_choices', models.ManyToManyField(blank=True, to='actions.tool')),
                ('weapon_proficiencies', models.ManyToManyField(to='actions.weapon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_playable', models.BooleanField(default=False)),
                ('inh_str', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('inh_dex', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('inh_con', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('inh_int', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('inh_wis', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('inh_cha', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3)),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('language_choices', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('condition_immunities', models.ManyToManyField(blank=True, to='rules.condition')),
                ('damage_immunities', models.ManyToManyField(blank=True, related_name='race_immunities', to='rules.damagetype')),
                ('damage_resistances', models.ManyToManyField(blank=True, related_name='race_resistances', to='rules.damagetype')),
                ('damage_vulnerabilities', models.ManyToManyField(blank=True, related_name='race_vulnerabilities', to='rules.damagetype')),
                ('features', models.ManyToManyField(blank=True, to='rules.feature')),
                ('languages', models.ManyToManyField(blank=True, to='rules.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background')),
            ],
            options={
                'order_with_respect_to': 'background',
            },
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background')),
            ],
            options={
                'order_with_respect_to': 'background',
            },
        ),
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background')),
            ],
            options={
                'order_with_respect_to': 'background',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traits.background')),
            ],
            options={
                'order_with_respect_to': 'background',
            },
        ),
    ]
