# Generated by Django 5.0.4 on 2024-09-20 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background'),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background'),
        ),
        migrations.AlterField(
            model_name='ideal',
            name='background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background'),
        ),
    ]
