# Generated by Django 5.0.4 on 2024-07-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='entityclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name']},
        ),
    ]
