# Generated by Django 5.0.4 on 2024-09-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_playablecharacter_bond_and_more'),
        ('traits', '0002_alter_bond_background_alter_flaw_background_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flaw',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='background',
        ),
        migrations.AlterUniqueTogether(
            name='ideal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ideal',
            name='background',
        ),
        migrations.AlterUniqueTogether(
            name='personality',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personality',
            name='background',
        ),
        migrations.AddField(
            model_name='background',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entityclass',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='progresstable',
            name='entity_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traits.entityclass'),
        ),
        migrations.AlterField(
            model_name='race',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='aligment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawfull Good'), ('LN', 'Lawfull Neutral'), ('LE', 'Lawfull Evil'), ('NG', 'Neutral Good'), ('NN', 'Neutral Neutral'), ('NE', 'Neutral Evil'), ('CG', 'Choatic Good'), ('CN', 'Choatic Neutral'), ('CE', 'Choatic Evil')], default=None, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Bond',
        ),
        migrations.DeleteModel(
            name='Flaw',
        ),
        migrations.DeleteModel(
            name='Ideal',
        ),
        migrations.DeleteModel(
            name='Personality',
        ),
    ]
