# Generated by Django 5.0.4 on 2024-07-08 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor_class', models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('gives_dex_bonus', models.BooleanField(default=False)),
                ('dex_bonus', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('required_str', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('spell_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('verbal', models.BooleanField(default=False)),
                ('somatic', models.BooleanField(default=False)),
                ('material', models.BooleanField(default=False)),
                ('materials', models.TextField(blank=True)),
                ('is_ritual', models.BooleanField(default=False)),
                ('casting_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('casting_measure', models.CharField(choices=[('a', 'Action'), ('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day')], max_length=3)),
                ('need_concentration', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_measure', models.CharField(choices=[('a', 'Action'), ('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dices', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('hit_dice', models.IntegerField(choices=[(4, 'D4'), (6, 'D6'), (8, 'D8'), (10, 'D10'), (12, 'D12'), (20, 'D20')], default=4, null=True)),
                ('bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('melee_weapon', models.BooleanField(default=False)),
                ('melee_range', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ranged_weapon', models.BooleanField(default=False)),
                ('min_range', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('max_range', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
