# Generated by Django 5.0.4 on 2024-07-03 21:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdventureGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default='cp', max_length=2)),
                ('weight', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default='cp', max_length=2)),
                ('weight', models.FloatField(default=0)),
                ('armor_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dex_bonus', models.BooleanField(default=False)),
                ('max_dex_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_str', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disadvantage_stealth', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('spell_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('verbal', models.BooleanField(default=False)),
                ('somatic', models.BooleanField(default=False)),
                ('material', models.BooleanField(default=False)),
                ('materials', models.TextField(blank=True)),
                ('is_ritual', models.BooleanField(default=False)),
                ('casting_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)])),
                ('casting_measure', models.CharField(choices=[('a', 'Action'), ('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day')], max_length=3)),
                ('need_concentration', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_measure', models.CharField(choices=[('a', 'Action'), ('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day')], max_length=3)),
                ('damage_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.damagetype')),
                ('magic_school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.magicschool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default='cp', max_length=2)),
                ('weight', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default='cp', max_length=2)),
                ('weight', models.FloatField(default=0)),
                ('hit_dices', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('dice_sides', models.IntegerField(choices=[(4, 'D4'), (6, 'D6'), (8, 'D8'), (10, 'D10'), (12, 'D12'), (20, 'D20')], default=4, null=True)),
                ('bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ranged_weapon', models.BooleanField(default=False)),
                ('normal_range', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_range', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category')),
                ('damage_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.damagetype')),
                ('property', models.ManyToManyField(blank=True, to='rules.weaponproperty')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
