# Generated by Django 5.0.4 on 2024-06-18 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Precio')),
                ('coin', models.CharField(choices=[('pc', 'pc'), ('pp', 'pp'), ('pe', 'pe'), ('po', 'po'), ('ppt', 'ppt')], default='pc', max_length=3, verbose_name='Moneda')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Peso')),
                ('weight_measure', models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)')),
                ('category', models.CharField(choices=[('Canalizadores Arcanos', 'Canalizadores Arcanos'), ('Canalizadores Druídicos', 'Canalizadores Druídicos'), ('Mercancías', 'Mercancías'), ('Munición', 'Munición'), ('Símbolos Sagrados', 'Símbolos Sagrados')], default=None, max_length=23, null=True, verbose_name='Categoría')),
                ('description', models.CharField(blank=True, max_length=1250, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Precio')),
                ('coin', models.CharField(choices=[('pc', 'pc'), ('pp', 'pp'), ('pe', 'pe'), ('po', 'po'), ('ppt', 'ppt')], default='pc', max_length=3, verbose_name='Moneda')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Peso')),
                ('weight_measure', models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)')),
                ('category', models.CharField(choices=[('Armaduras Ligeras', 'Armaduras Ligeras'), ('Armaduras Medianas', 'Armaduras Medianas'), ('Armaduras Pesadas', 'Armaduras Pesadas'), ('Escudos', 'Escudos')], max_length=18, verbose_name='Categoría')),
                ('armor_class', models.PositiveSmallIntegerField(verbose_name='CA')),
                ('dexterity_bonus', models.BooleanField(default=False, verbose_name='Bonificador de Destreza')),
                ('min_strength', models.PositiveSmallIntegerField(default=0, verbose_name='FUE')),
                ('disadvantage_stealth', models.BooleanField(default=False, verbose_name='Desventaja en Sigilo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('magic_school', models.CharField(choices=[('Abjuración', 'Abjuración'), ('Adivinación', 'Adivinación'), ('Conjuración', 'Conjuración'), ('Encantamiento', 'Encantamiento'), ('Evocación', 'Evocación'), ('Ilusión', 'Ilusión'), ('Nigromancia', 'Nigromancia'), ('Transmutación', 'Transmutación')], max_length=13, verbose_name='Escuela de Magia')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Nivel')),
                ('description', models.CharField(max_length=1250, verbose_name='Descripción')),
                ('verbal', models.BooleanField(default=False, verbose_name='Verbal')),
                ('somatic', models.BooleanField(default=False, verbose_name='Somático')),
                ('material', models.BooleanField(default=False, verbose_name='Material')),
                ('material_description', models.CharField(blank=True, max_length=250, verbose_name='Materiales')),
                ('spell_range', models.SmallIntegerField(help_text='[-1]: Lanzador; [0]: Toque', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Alcance (Casillas)')),
                ('launch_time', models.PositiveSmallIntegerField(default=0, verbose_name='Tiempo de Lanzamiento')),
                ('launch_measure', models.CharField(choices=[('a', 'Acción'), ('s', 'Segundo'), ('min', 'Minuto'), ('h', 'Hora'), ('d', 'Día')], max_length=6, verbose_name='Unidad de Tiempo (Tiempo de Lanzamiento)')),
                ('concentration', models.BooleanField(default=False, verbose_name='Concentración')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duración')),
                ('duration_measure', models.CharField(choices=[('a', 'Acción'), ('s', 'Segundo'), ('min', 'Minuto'), ('h', 'Hora'), ('d', 'Día')], max_length=3, verbose_name='Unidad de Tiempo (Duración)')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Precio')),
                ('coin', models.CharField(choices=[('pc', 'pc'), ('pp', 'pp'), ('pe', 'pe'), ('po', 'po'), ('ppt', 'ppt')], default='pc', max_length=3, verbose_name='Moneda')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Peso')),
                ('weight_measure', models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)')),
                ('category', models.CharField(choices=[('Herramientas de Artesano', 'Herramienta de Artesano'), ('Instrumentos Musicales', 'Instrumentos Musicales'), ('Juegos', 'Juegos')], default=None, max_length=24, null=True, verbose_name='Categoría')),
                ('description', models.CharField(blank=True, max_length=1250, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Precio')),
                ('coin', models.CharField(choices=[('pc', 'pc'), ('pp', 'pp'), ('pe', 'pe'), ('po', 'po'), ('ppt', 'ppt')], default='pc', max_length=3, verbose_name='Moneda')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Peso')),
                ('weight_measure', models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)')),
                ('category', models.CharField(choices=[('Armas cuerpo a cuerpo sencillas', 'Armas cuerpo a cuerpo sencillas'), ('Armas a distancia sencillas', 'Armas a distancia sencillas'), ('Armas cuerpo a cuerpo marciales', 'Armas cuerpo a cuerpo marciales'), ('Armas a distancia marciales', 'Armas a distancia marciales')], max_length=31, verbose_name='Categoría')),
                ('hit_dices', models.PositiveSmallIntegerField(default=1, verbose_name='Nº dados')),
                ('dice_sides', models.PositiveSmallIntegerField(default=4, verbose_name='Nº caras')),
                ('modifier', models.PositiveSmallIntegerField(default=0, verbose_name='Modificador')),
                ('damage_type', models.CharField(choices=[('Contundente', ' Contundente'), ('Cortante', 'Cortante'), ('Perforante', 'Perforante')], max_length=11, verbose_name='Tipo de Daño')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
