# Generated by Django 5.0.4 on 2024-07-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('rules', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='entity_class',
            field=models.ManyToManyField(to='traits.entityclass'),
        ),
        migrations.AddField(
            model_name='spell',
            name='magic_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.magicschool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.damagetype'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='property',
            field=models.ManyToManyField(blank=True, to='rules.weaponproperty'),
        ),
    ]
