# Generated by Django 5.0.4 on 2024-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='class_spell',
            field=models.ManyToManyField(to='characters.entityclass', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='property',
            field=models.ManyToManyField(to='actions.property', verbose_name='Propiedad'),
        ),
    ]
