# Generated by Django 5.0.4 on 2024-06-11 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
        ),
        migrations.RemoveField(
            model_name='adventurerequipment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='adventurerequipment',
            name='category',
            field=models.CharField(choices=[('Canalizadores Arcanos', 'Canalizadores Arcanos'), ('Canalizadores Druídicos', 'Canalizadores Druídicos'), ('Mercancías', 'Mercancías'), ('Munición', 'Munición'), ('Símbolos Sagrados', 'Símbolos Sagrados')], default=None, max_length=23, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='adventurerequipment',
            name='measuring_unit',
            field=models.CharField(choices=[('Área', [('c2', 'Casilla Cuadrada'), ('cm2', 'Centímetro Cuadrado'), ('km2', 'Kilómetro Cuadrado'), ('mi2', 'Milla Cuadrada'), ('m2', 'Metro Cuadrado'), ('ft2', 'Pie Cuadrado'), ('in2', 'Pulgada Cuadrada'), ('yd2', 'Yarda Cuadrada')]), ('Longitud', [('c', 'Casilla'), ('cm', 'Centímetro'), ('km', 'Kilómetro'), ('mi', 'Milla'), ('m', 'Metro'), ('ft', 'Pie'), ('in', 'Pulgada'), ('yd', 'Yarda')]), ('Masa', [('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')]), ('Velocidad', [('c/a', 'Casilla * Acción'), ('ft/a', 'Pie * Acción'), ('m/a', 'Metro * Acción'), ('km/h', 'Kilómetro * Hora'), ('mi/h', 'Milla * Hora')]), ('Tiempo', [('a', 'Acción'), ('s', 'Segundo'), ('min', 'Minuto'), ('h', 'Hora'), ('d', 'Día')]), ('Volumen', [('gal', 'Galón'), ('lt', 'Litro'), ('ml', 'Mililitro'), ('pt', 'Pinta')])], default=None, max_length=4, null=True, verbose_name='Magnitud (Medida)'),
        ),
        migrations.AlterField(
            model_name='adventurerequipment',
            name='weight_measure',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='armor_class',
            field=models.PositiveSmallIntegerField(verbose_name='CA'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='weight_measure',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration_measure',
            field=models.CharField(choices=[('a', 'Acción'), ('s', 'Segundo'), ('min', 'Minuto'), ('h', 'Hora'), ('d', 'Día')], max_length=3, verbose_name='Unidad de Tiempo (Duración)'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='launch_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tiempo de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_range',
            field=models.SmallIntegerField(help_text='[-1]: Lanzador; [0]: Toque', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Alcance (Casillas)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Herramientas de Artesano', 'Herramienta de Artesano'), ('Instrumentos Musicales', 'Instrumentos Musicales'), ('Juegos', 'Juegos')], default=None, max_length=24, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='weight_measure',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='property',
            field=models.ManyToManyField(default=None, null=True, to='actions.property', verbose_name='Propiedad'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight_measure',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilogramo'), ('lb', 'Libra'), ('oz', 'Onza')], default='lb', max_length=2, null=True, verbose_name='Magnitud (Peso)'),
        ),
    ]
