# Generated by Django 5.0.4 on 2024-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurerequipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (lb)'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (lb)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (lb)'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (lb)'),
        ),
    ]
