# Generated by Django 5.0.4 on 2024-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurerequipment',
            name='coin',
            field=models.CharField(choices=[('pc', 'Copper'), ('pp', 'Silver'), ('pe', 'Electrum'), ('po', 'Gold'), ('ppt', 'Platinum')], default='pc', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='coin',
            field=models.CharField(choices=[('pc', 'Copper'), ('pp', 'Silver'), ('pe', 'Electrum'), ('po', 'Gold'), ('ppt', 'Platinum')], default='pc', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='coin',
            field=models.CharField(choices=[('pc', 'Copper'), ('pp', 'Silver'), ('pe', 'Electrum'), ('po', 'Gold'), ('ppt', 'Platinum')], default='pc', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='coin',
            field=models.CharField(choices=[('pc', 'Copper'), ('pp', 'Silver'), ('pe', 'Electrum'), ('po', 'Gold'), ('ppt', 'Platinum')], default='pc', max_length=3, verbose_name='Moneda'),
        ),
    ]
