# Generated by Django 5.0.4 on 2024-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(blank=True, max_length=1250, verbose_name='Descripción'),
        ),
    ]
