# Generated by Django 5.0.4 on 2024-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_trinket_remove_adventurerequipment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='property',
            field=models.ManyToManyField(blank=True, to='actions.property', verbose_name='Propiedad'),
        ),
    ]
