# Generated by Django 5.0.4 on 2024-06-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_adventurerequipment_weight_alter_armor_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='hit_dice',
        ),
        migrations.AddField(
            model_name='weapon',
            name='dice_sides',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Nº caras'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='hit_dices',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nº dados'),
        ),
    ]
