# Generated by Django 5.0.4 on 2024-10-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_adventuregear_category_and_more'),
        ('rules', '0003_rename_armor_list_feature_armors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuregear',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AlterField(
            model_name='adventuregear',
            name='coin',
            field=models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='coin',
            field=models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='coin',
            field=models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.category'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='coin',
            field=models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], default=None, max_length=2, null=True),
        ),
    ]
