# Generated by Django 5.0.4 on 2024-06-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_weapon_hit_dice_weapon_dice_sides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='property',
            field=models.ManyToManyField(blank=True, to='actions.property', verbose_name='Propiedad'),
        ),
    ]
