# Generated by Django 5.0.4 on 2024-08-13 15:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0002_initial'),
        ('traits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hit_points', models.PositiveSmallIntegerField(default=10)),
                ('str_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('dex_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('con_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('int_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('wis_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('cha_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('challenge', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(34), django.core.validators.MinValueValidator(1)])),
                ('legendary_creature', models.BooleanField(default=False)),
                ('armor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_armor', to='actions.armor')),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hit_points', models.PositiveSmallIntegerField(default=10)),
                ('str_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('dex_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('con_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('int_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('wis_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('cha_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30)])),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('inspiration', models.BooleanField(default=False)),
                ('copper', models.PositiveSmallIntegerField(default=0)),
                ('silver', models.PositiveSmallIntegerField(default=0)),
                ('electrum', models.PositiveSmallIntegerField(default=0)),
                ('gold', models.PositiveSmallIntegerField(default=0)),
                ('platinum', models.PositiveSmallIntegerField(default=0)),
                ('adventure_gears', models.ManyToManyField(blank=True, to='actions.adventuregear')),
                ('armor', models.ManyToManyField(blank=True, to='actions.armor')),
                ('background', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background')),
                ('bond', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.bond')),
                ('entity_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.entityclass')),
                ('flaw', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.flaw')),
                ('ideal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.ideal')),
                ('personality', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.personality')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell')),
                ('tools', models.ManyToManyField(blank=True, to='actions.tool')),
                ('trinkets', models.ManyToManyField(blank=True, to='actions.trinket')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
