# Generated by Django 5.0.4 on 2024-06-19 16:53

import apps.characters.models
import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('traits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('hit_dice', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(4)], verbose_name='Dado de Golpe')),
                ('max_tool_proficiencies_choices', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Competencia con Herramientas Disponibles')),
                ('max_skill_choices', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Habilidades Disponibles')),
                ('armor_proficiencies', models.ManyToManyField(to='actions.armor', verbose_name='Competencias con Armaduras')),
                ('saving_throws', models.ManyToManyField(max_length=2, to='traits.savingthrow', verbose_name='Tiradas de Salvación')),
                ('skill_choices', models.ManyToManyField(to='traits.skill', verbose_name='Lista de Habilidades Disponibles')),
                ('tool_proficiencies_choices', models.ManyToManyField(blank=True, to='actions.tool', verbose_name='Lista de Competencias con Herramientas Disponibles')),
                ('weapon_proficiencies', models.ManyToManyField(to='actions.weapon', verbose_name='Competencias con Armas')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('is_playable', models.BooleanField(default=False, verbose_name='¿Jugable?')),
                ('language_choices', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Idiomas a elección')),
                ('size', models.CharField(choices=[('XS', 'Diminuto'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Enorme'), ('XXL', 'Gigante')], max_length=3, verbose_name='Tamaño')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Velocidad')),
                ('strength', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='FUE')),
                ('dexterity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='DES')),
                ('constitution', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='CON')),
                ('intelligence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='INT')),
                ('wisdom', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='SAB')),
                ('charisma', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='CAR')),
                ('features', models.ManyToManyField(blank=True, to='traits.feature', verbose_name='Rasgos')),
                ('languages', models.ManyToManyField(blank=True, to='traits.language', verbose_name='Idiomas')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('aligment', models.CharField(choices=[('LB', 'Legal Bueno'), ('LN', 'Legal Neutro'), ('LM', 'Legal Malvado'), ('NB', 'Neutral Bueno'), ('NN', 'Neutral'), ('NM', 'Neutral Malvado'), ('CB', 'Caótico Bueno'), ('CN', 'Caótico Neutro'), ('CM', 'Caótico Malvado')], max_length=2, verbose_name='Alineamiento')),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='FUE Base')),
                ('calculated_strength', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_strength, editable=False, verbose_name='FUE Total')),
                ('strength_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_strength_modifier, editable=False, verbose_name='FUE Modificador')),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='DES Base')),
                ('calculated_dexterity', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_dexterity, editable=False, verbose_name='DES Total')),
                ('dexterity_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_dexterity_modifier, editable=False, verbose_name='DES Modificador')),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='CON Base')),
                ('calculated_constitution', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_constitution, editable=False, verbose_name='CON Total')),
                ('constitution_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_constitution_modifier, editable=False, verbose_name='CON Modificador')),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='INT Base')),
                ('calculated_intelligence', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_intelligence, editable=False, verbose_name='INT Total')),
                ('intelligence_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_intelligence_modifier, editable=False, verbose_name='INT Modificador')),
                ('wisdom', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='SAB Base')),
                ('calculated_wisdom', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_wisdom, editable=False, verbose_name='SAB Total')),
                ('wisdom_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_wisdom_modifier, editable=False, verbose_name='SABModificador')),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='CAR Base')),
                ('calculated_charisma', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_charisma, editable=False, verbose_name='CAR Total')),
                ('charisma_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_charisma_modifier, editable=False, verbose_name='CAR Modificador')),
                ('challenge', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(34), django.core.validators.MinValueValidator(1)], verbose_name='Nivel de Desafío')),
                ('proficiency_bonus', models.PositiveSmallIntegerField(default=apps.characters.models.Monster.calculate_proficiency_bonus, editable=False, verbose_name='Bonificador de Competencia')),
                ('Tiradas de Salvación', models.ManyToManyField(blank=True, to='traits.savingthrow')),
                ('armor', models.ManyToManyField(blank=True, to='actions.armor', verbose_name='Armadura')),
                ('equipment', models.ManyToManyField(blank=True, to='actions.adventuregear', verbose_name='Equipo de Aventurero')),
                ('skills', models.ManyToManyField(blank=True, to='traits.skill', verbose_name='Habilidades')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell', verbose_name='Conjuros')),
                ('tools', models.ManyToManyField(blank=True, to='actions.tool', verbose_name='Herramientas')),
                ('trinkets', models.ManyToManyField(blank=True, to='actions.trinket', verbose_name='Baratijas')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon', verbose_name='Armas')),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('aligment', models.CharField(choices=[('LB', 'Legal Bueno'), ('LN', 'Legal Neutro'), ('LM', 'Legal Malvado'), ('NB', 'Neutral Bueno'), ('NN', 'Neutral'), ('NM', 'Neutral Malvado'), ('CB', 'Caótico Bueno'), ('CN', 'Caótico Neutro'), ('CM', 'Caótico Malvado')], max_length=2, verbose_name='Alineamiento')),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='FUE Base')),
                ('calculated_strength', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_strength, editable=False, verbose_name='FUE Total')),
                ('strength_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_strength_modifier, editable=False, verbose_name='FUE Modificador')),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='DES Base')),
                ('calculated_dexterity', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_dexterity, editable=False, verbose_name='DES Total')),
                ('dexterity_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_dexterity_modifier, editable=False, verbose_name='DES Modificador')),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='CON Base')),
                ('calculated_constitution', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_constitution, editable=False, verbose_name='CON Total')),
                ('constitution_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_constitution_modifier, editable=False, verbose_name='CON Modificador')),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='INT Base')),
                ('calculated_intelligence', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_intelligence, editable=False, verbose_name='INT Total')),
                ('intelligence_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_intelligence_modifier, editable=False, verbose_name='INT Modificador')),
                ('wisdom', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='SAB Base')),
                ('calculated_wisdom', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_wisdom, editable=False, verbose_name='SAB Total')),
                ('wisdom_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_wisdom_modifier, editable=False, verbose_name='SABModificador')),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='CAR Base')),
                ('calculated_charisma', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_charisma, editable=False, verbose_name='CAR Total')),
                ('charisma_modifier', models.PositiveSmallIntegerField(default=apps.core.models.Entity.calculate_charisma_modifier, editable=False, verbose_name='CAR Modificador')),
                ('inspiration', models.BooleanField(default=False, verbose_name='Inspiración')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Experiencia')),
                ('level', models.PositiveSmallIntegerField(default=apps.characters.models.Character.calculate_level, editable=False, verbose_name='Nivel')),
                ('proficiency_bonus', models.PositiveSmallIntegerField(default=apps.characters.models.Character.calculate_proficiency_bonus, editable=False, verbose_name='Bonificador por Competencia')),
                ('Tiradas de Salvación', models.ManyToManyField(to='traits.savingthrow')),
                ('armor', models.ManyToManyField(blank=True, to='actions.armor', verbose_name='Armadura')),
                ('armor_proficiencies', models.ManyToManyField(related_name='proficient_characters', to='actions.armor', verbose_name='Competencias con Armaduras')),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background', verbose_name='Trasfondo')),
                ('equipment', models.ManyToManyField(blank=True, to='actions.adventuregear', verbose_name='Equipo de Aventurero')),
                ('languages', models.ManyToManyField(to='traits.language', verbose_name='Idiomas')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
                ('skills', models.ManyToManyField(to='traits.skill', verbose_name='Habilidades')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell', verbose_name='Conjuros')),
                ('tool_proficiencies', models.ManyToManyField(related_name='proficient_characters', to='actions.tool', verbose_name='Competencias con Herramientas')),
                ('tools', models.ManyToManyField(blank=True, to='actions.tool', verbose_name='Herramientas')),
                ('trinkets', models.ManyToManyField(blank=True, to='actions.trinket', verbose_name='Baratijas')),
                ('weapon_proficiencies', models.ManyToManyField(related_name='proficient_characters', to='actions.weapon', verbose_name='Competencias con Armas')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon', verbose_name='Armas')),
                ('entity_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.entityclass', verbose_name='Clase')),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
