# Generated by Django 5.0.4 on 2024-07-03 21:47

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('traits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('dexterity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('constitution', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('wisdom', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('charisma', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('challenge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(34), django.core.validators.MinValueValidator(1)])),
                ('proficiency_bonus', models.IntegerField(default=apps.characters.models.NonPlayableCharacter.calculate_proficiency_bonus, editable=False)),
                ('armor', models.ManyToManyField(blank=True, to='actions.armor')),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('dexterity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('constitution', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('wisdom', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('charisma', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('inspiration', models.BooleanField(default=False)),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.IntegerField(default=apps.characters.models.PlayableCharacter.calculate_level, editable=False)),
                ('proficiency_bonus', models.IntegerField(default=apps.characters.models.PlayableCharacter.calculate_proficiency_bonus, editable=False)),
                ('copper_pieces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('silver_pieces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('electrum_pieces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_pieces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('platinum_pieces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('adventure_gear', models.ManyToManyField(blank=True, to='actions.adventuregear')),
                ('armor', models.ManyToManyField(blank=True, to='actions.armor')),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.background')),
                ('entity_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.entityclass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race')),
                ('spells', models.ManyToManyField(blank=True, to='actions.spell')),
                ('tools', models.ManyToManyField(blank=True, to='actions.tool')),
                ('trinkets', models.ManyToManyField(blank=True, to='actions.trinket')),
                ('weapons', models.ManyToManyField(blank=True, to='actions.weapon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
