# Generated by Django 5.0.4 on 2024-06-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_trinket_remove_adventurerequipment_amount_and_more'),
        ('characters', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='trinkts',
            field=models.ManyToManyField(default=None, null=True, to='actions.trinket', verbose_name='Baratijas'),
        ),
        migrations.AddField(
            model_name='monster',
            name='trinkts',
            field=models.ManyToManyField(default=None, null=True, to='actions.trinket', verbose_name='Baratijas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(default=None, null=True, to='actions.armor', verbose_name='Armadura'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(default=None, null=True, to='actions.adventurerequipment', verbose_name='Equipo de Aventurero'),
        ),
        migrations.AlterField(
            model_name='character',
            name='features',
            field=models.ManyToManyField(default=None, null=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(default=None, null=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiencies',
            field=models.ManyToManyField(default=None, null=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(default=None, null=True, to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tools',
            field=models.ManyToManyField(default=None, null=True, to='actions.tool', verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(default=None, null=True, to='actions.weapon', verbose_name='Armas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor',
            field=models.ManyToManyField(default=None, null=True, to='actions.armor', verbose_name='Armadura'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='equipment',
            field=models.ManyToManyField(default=None, null=True, to='actions.adventurerequipment', verbose_name='Equipo de Aventurero'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='features',
            field=models.ManyToManyField(default=None, null=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.ManyToManyField(default=None, null=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='proficiencies',
            field=models.ManyToManyField(default=None, null=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='spells',
            field=models.ManyToManyField(default=None, null=True, to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='tools',
            field=models.ManyToManyField(default=None, null=True, to='actions.tool', verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapons',
            field=models.ManyToManyField(default=None, null=True, to='actions.weapon', verbose_name='Armas'),
        ),
    ]
