# Generated by Django 5.0.4 on 2024-09-20 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('traits', '0002_alter_bond_background_alter_flaw_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonplayablecharacter',
            name='race',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race'),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='race',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race'),
        ),
    ]
