# Generated by Django 5.0.4 on 2024-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copper_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Cobre'),
        ),
        migrations.AddField(
            model_name='character',
            name='electrum_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Electro'),
        ),
        migrations.AddField(
            model_name='character',
            name='gold_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Oro'),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Platino'),
        ),
        migrations.AddField(
            model_name='character',
            name='silver_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Plata'),
        ),
        migrations.AddField(
            model_name='monster',
            name='copper_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Cobre'),
        ),
        migrations.AddField(
            model_name='monster',
            name='electrum_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Electro'),
        ),
        migrations.AddField(
            model_name='monster',
            name='gold_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Oro'),
        ),
        migrations.AddField(
            model_name='monster',
            name='platinum_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Platino'),
        ),
        migrations.AddField(
            model_name='monster',
            name='silver_pieces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Piezas de Plata'),
        ),
    ]
