# Generated by Django 5.0.4 on 2024-05-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0002_initial'),
        ('characters', '0001_initial'),
        ('matches', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player', verbose_name='Jugador'),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies_entity',
            field=models.ManyToManyField(blank=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AddField(
            model_name='entityclass',
            name='proficiencies_class',
            field=models.ManyToManyField(to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AddField(
            model_name='character',
            name='class_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.entityclass', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='monster',
            name='features_entity',
            field=models.ManyToManyField(blank=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AddField(
            model_name='monster',
            name='languages_entity',
            field=models.ManyToManyField(blank=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AddField(
            model_name='monster',
            name='proficiencies_entity',
            field=models.ManyToManyField(blank=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AddField(
            model_name='monster',
            name='spells',
            field=models.ManyToManyField(to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AddField(
            model_name='race',
            name='features_race',
            field=models.ManyToManyField(blank=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AddField(
            model_name='race',
            name='languages_race',
            field=models.ManyToManyField(blank=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AddField(
            model_name='monster',
            name='race_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='character',
            name='race_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='Raza'),
        ),
    ]
