# Generated by Django 5.0.4 on 2024-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_weapon_property'),
        ('characters', '0002_character_trinkts_monster_trinkts_and_more'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, to='actions.armor', verbose_name='Armadura'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='actions.adventurerequipment', verbose_name='Equipo de Aventurero'),
        ),
        migrations.AlterField(
            model_name='character',
            name='features',
            field=models.ManyToManyField(blank=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiencies',
            field=models.ManyToManyField(blank=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tools',
            field=models.ManyToManyField(blank=True, to='actions.tool', verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='trinkts',
            field=models.ManyToManyField(blank=True, to='actions.trinket', verbose_name='Baratijas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='actions.weapon', verbose_name='Armas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor',
            field=models.ManyToManyField(blank=True, to='actions.armor', verbose_name='Armadura'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='actions.adventurerequipment', verbose_name='Equipo de Aventurero'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='features',
            field=models.ManyToManyField(blank=True, to='traits.feature', verbose_name='Rasgos'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.ManyToManyField(blank=True, to='traits.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='proficiencies',
            field=models.ManyToManyField(blank=True, to='traits.proficiency', verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='spells',
            field=models.ManyToManyField(blank=True, to='actions.spell', verbose_name='Conjuros'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='tools',
            field=models.ManyToManyField(blank=True, to='actions.tool', verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='trinkts',
            field=models.ManyToManyField(blank=True, to='actions.trinket', verbose_name='Baratijas'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='actions.weapon', verbose_name='Armas'),
        ),
    ]
