# Generated by Django 5.0.4 on 2024-09-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_adventuregear_category_and_more'),
        ('characters', '0002_alter_nonplayablecharacter_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playablecharacter',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='playablecharacter',
            name='flaw',
        ),
        migrations.RemoveField(
            model_name='playablecharacter',
            name='ideal',
        ),
        migrations.RemoveField(
            model_name='playablecharacter',
            name='personality',
        ),
        migrations.AlterField(
            model_name='nonplayablecharacter',
            name='armor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_armor', to='actions.armor'),
        ),
    ]
