# Generated by Django 5.0.4 on 2024-10-01 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_adventuregear_category_and_more'),
        ('characters', '0003_remove_playablecharacter_bond_and_more'),
        ('traits', '0004_alter_background_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonplayablecharacter',
            name='armor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_armor', to='actions.armor'),
        ),
        migrations.AlterField(
            model_name='nonplayablecharacter',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race'),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.race'),
        ),
    ]
