# Generated by Django 5.0.4 on 2024-07-04 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('item_type', models.CharField(choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('sub_category', models.CharField(choices=[('M', 'Magic'), ('P', 'Pshysic')], default='P', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('item_type', models.CharField(choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stat', models.CharField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], max_length=3)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('armors', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('languages', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('skills', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tools', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weapons', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('strength', models.BooleanField(default=False)),
                ('dexterity', models.BooleanField(default=False)),
                ('constitution', models.BooleanField(default=False)),
                ('intelligence', models.BooleanField(default=False)),
                ('wisdom', models.BooleanField(default=False)),
                ('charisma', models.BooleanField(default=False)),
                ('description', models.TextField(unique=True)),
                ('armors_list', models.ManyToManyField(blank=True, to='actions.armor')),
                ('condition_immunity', models.ManyToManyField(blank=True, related_name='condition_immunity_by_feature', to='rules.condition')),
                ('damage_immunity', models.ManyToManyField(blank=True, related_name='damage_immunity_by_feature', to='rules.damagetype')),
                ('damage_resistance', models.ManyToManyField(blank=True, related_name='damage_resistance_by_feature', to='rules.damagetype')),
                ('damage_vulnerability', models.ManyToManyField(blank=True, related_name='damage_vulnerability_by_feature', to='rules.damagetype')),
                ('tools_list', models.ManyToManyField(blank=True, to='actions.tool')),
                ('weapons_list', models.ManyToManyField(blank=True, to='actions.weapon')),
                ('languages_list', models.ManyToManyField(blank=True, to='rules.language')),
                ('skills_list', models.ManyToManyField(blank=True, to='rules.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
