# Generated by Django 5.0.4 on 2024-09-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='item_type',
            field=models.CharField(blank=True, choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='item_type',
            field=models.CharField(blank=True, choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True),
        ),
    ]
