# Generated by Django 5.0.4 on 2024-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_category_item_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='armor_list',
            new_name='armors',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='language_list',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='skill_list',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='tool_list',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='weapon_list',
            new_name='weapons',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='armor_choices',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='language_choices',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='skill_choices',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='tool_choices',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='weapon_choices',
        ),
        migrations.AlterField(
            model_name='category',
            name='item_type',
            field=models.CharField(choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='item_type',
            field=models.CharField(choices=[('A', 'Armor'), ('G', 'Gear'), ('T', 'Tool'), ('W', 'Weapon')], default=None, max_length=1, null=True),
        ),
    ]
