# Generated by Django 5.0.4 on 2024-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
