# Generated by Django 5.0.4 on 2024-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_nonplayablecharacter_armor_and_more'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='characters',
            field=models.ManyToManyField(blank=True, to='characters.playablecharacter'),
        ),
    ]
